FROM ghcr.io/ublue-os/fsync-kernel:42 AS kernel_cache

RUN --mount=type=cache,dst=/var/cache/rpm-ostree \
    --mount=type=bind,from=kernel_cache,source=/tmp/rpms,target=/tmp/kernel-rpms \
    rpm-ostree cliwrap install-to-root
