name: T2 Kansei Image Build
on:
  schedule:
    - cron: "00 6 * * *" # build after 02:00 US/Eastern every day
                          # (ublue main images build a bit after 03:00 UTC)
  # push:
  #   paths-ignore: # don't rebuild if only documentation has changed
  #     - "**.md"
      
  pull_request:
  workflow_dispatch: # allow manually triggering builds
jobs:
  bluebuild:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          #- t2-atomic-cosmic.yml
          #- t2-atomic-cosmic-gnome.yml
          #- t2-atomic-cosmic-plasma.yml
          - t2-atomic-kansei.yml
          #- t2-atomic-gnome.yml
          #- t2-atomic-hyprland.yml
          #- t2-atomic-lxqt.yml
          #- t2-atomic-plasma.yml
          #- t2-atomic-plasma-kansei.yml
          #- t2-atomic-sway.yml
          - t2-atomic-sway-kansei.yml

    steps:
       # the build is fully handled by the reusable github action
      - name: Image Build
        uses: blue-build/github-action@v1.6
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
